name: build-deploy
on:
  push:
    branches:
      - 'main'
env:
  docker_image: ghcr.io/${{ github.repository }}:${{ github.sha}}

jobs:
  build-push:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v3
      - name: Gradle build
        run: ./gradlew build
      - name: Build and push image and SBOM to OCI registry
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: oppgavehandtering
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
  deploy-dev:
    name: Deploy to dev
    needs: build-push
    runs-on: ubuntu-latest
    environment: dev-gcp:oppgavehandtering
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app-dev.yaml
          VAR: image=${{ needs.build-push.outputs.image }}
#  deploy-prod:
#    if: github.ref == 'refs/heads/main'
#    name: Deploy to prod
#    needs: build-push
#    runs-on: ubuntu-latest
#    environment: prod-gcp:oppgavehandtering
#    steps:
#      - uses: actions/checkout@v3
#      - uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{secrets.NAIS_DEPLOY_APIKEY}}
#          CLUSTER: prod-gcp
#          RESOURCE: .nais/app-prod.yaml
#          VAR: image=${{ env.docker_image }}